### ISSUE TITLE
Dictionary Key Typo in 'beams.py'

### ISSUE THREAD

**Issue by jindama** [jy-tang/pyDFCSR#9]
Inside beams.py, in the definition of check_inputs, there is a typo at the third branch of the if statement. 'particleGroup_h5' should be 'ParticleGroup_h5' in order for the program to be able to process h5 formatted input files. As-is, the code will throw an error if the user attempts to use the ParticleGroup input key inside the simulation config.

**Comment by jy-tang** [comment]
PR has been merged
